import { AppContextProvider } from '@/context/app.context';
import { ROBOTO_FONT } from '@/libs/mui/constants';
import { MuiProvider } from '@/libs/mui/mui-provider';
import { NextAuthProvider } from '@/libs/next-auth/next-auth-provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Booking App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // "next-intl"
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={ROBOTO_FONT.variable}>
        {/* "next-intl" */}
        <NextIntlClientProvider messages={messages}>
          <MuiProvider>
            <NextAuthProvider>
              <AppContextProvider>{children}</AppContextProvider>
            </NextAuthProvider>
          </MuiProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
