import { AppHeader } from '@/components/headers/app-header';
import { AppContextProvider } from '@/context/app.context';
import { MuiProvider } from '@/libs/mui/provider';
import { robotoFont } from '@/libs/mui/robot-font';
import { NextAuthProvider } from '@/libs/next-auth/next-auth-provider';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // "next-intl"
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={robotoFont.variable}>
        <MuiProvider>
          {/* "next-intl" */}
          <NextIntlClientProvider messages={messages}>
            <NextAuthProvider>
              <AppContextProvider>
                <AppHeader />
                {children}
              </AppContextProvider>
            </NextAuthProvider>
          </NextIntlClientProvider>
        </MuiProvider>
      </body>
    </html>
  );
}
