import type { Metadata } from 'next';

import { MuiProvider } from '@/libs/mui/mui-provider';
import { robotoFont } from '@/libs/mui/robot-font';

// Direct imports
import '@/assets/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoFont.variable}>
        <MuiProvider>{children}</MuiProvider>
      </body>
    </html>
  );
}
